version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    rebase-strategy: auto
    labels:
      - "dependencies"
    commit-message:
      prefix: 'Dependencies updated:'
    assignees:
      - 'woodemai'
    reviewers:
      - 'woodemai'